import { StackConfig, EXTERNAL_SKILL_PACKAGES, BACKEND_FRAMEWORKS } from '../config/options';

export function generateReadme(config: StackConfig): string {
  const selectedBackend = BACKEND_FRAMEWORKS.find(f => f.id === config.backendFramework)?.label || 'None';
  
  const allExternalSkills = Object.values(EXTERNAL_SKILL_PACKAGES).flat();
  const selectedExternals = config.externalSkills.map(id => allExternalSkills.find(s => s.id === id)).filter(Boolean);

  let externalSkillsSection = '';
  if (selectedExternals.length > 0) {
    externalSkillsSection = `\n## External Agent Skills\nWe included a \`setup-skills.sh\` (and \`setup-skills.bat\`) file to easily install the online skills you selected:\n`;
    selectedExternals.forEach(s => {
      externalSkillsSection += `- **${s!.name}**: \`${s!.installCommand}\`\n`;
    });
  }

  return `# ${config.projectName}

This robust starter template was generated by the **AI Hub Angular Stack Builder**.

## Stack Configuration
- **Framework**: Angular v${config.angularVersion}
- **UI Framework**: ${config.uiFramework.toUpperCase()}
- **PrimeNG**: ${config.primeNgVersion === 'none' ? 'None' : `v${config.primeNgVersion}`}
- **Backend Framework**: ${selectedBackend}
- **Linting**: ${config.linting.toUpperCase()}
- **Testing**: ${config.testing.toUpperCase()}
- **Integrated Editors**: ${config.editors.join(', ')}

## AI Integrations
${config.includeAiSkills ? `- Included ${config.selectedSkills.length} AI Hub skills.\n` : ''}
${config.includeBuiltinSkills ? `- Included standard Built-in best practice guidelines.\n` : ''}
${config.includeRules ? `- Included IDE compilation behavior rules (.cursor/rules).\n` : ''}

You can find the generated AI developer rules in the \`.ai/\` directory.${externalSkillsSection}

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run development server:
   \`\`\`bash
   npm run start
   \`\`\`

3. Build production bundle:
   \`\`\`bash
   npm run build
   \`\`\`
   
Happy coding!
`;
}
